### ISSUE TITLE
CRW-Dev Usage

### ISSUE THREAD

**Issue by rajicon** [timoschick/form-context-model#3]
Is there any scripts showing example usage of the CRW Dev set?  It seems to have slightly different format than the original CRW set  (for example, it seems that the unknown word is removed from the contexts here.  How do we determine the unknown word's original location in order to find the neighboring context words? Or do we just add every word in the context sentence?)

**Comment by timoschick** [comment]
Hi rajicon, indeed it is not possible to recover the original position of the removed word from the CRW dev set in its current form. The model for which we originally created this set didn't take word ordering into account so we did not mark its original position. If this is something that you require, please let me know and I will try and reconstruct this information.

**Comment by rajicon** [comment]
Hi,

So to clarify, when using the contexts for CRW, you did not use any sort of window, correct?  You take every word in the sentence as a context word?

Also, is it possible to access the script that calculates the CRW dev results (if not, it isn't a big deal, but it would be helpful if possible).

**Comment by rajicon** [comment]
Hi,

I would like the position information if possible.  Unless I'm mistaken, even in FCM the window size matters, so in order to repeat the experiment we need it, right?

Thanks!

**Comment by timoschick** [comment]
Hi, 

I have now replaced the sentences with versions where the rare words are left intact (you can still find the previous version in the subdirectory `without_target_word`). You are fully correct, to get the correct window one needs to know the position of the rare word.

With regards to an evaluation script for CRW-DEV, you should be fine with taking the original CRW evaluation script and simply replacing the file names.

Best regards

Timo

**Comment by rajicon** [comment]
Thanks!
