### ISSUE TITLE
The character-level n-gram vocab

### ISSUE THREAD

**Issue by yuanzhiKe** [timoschick/form-context-model#4]
Hello.
Thank you for sharing the implementation of your works!

We are trying to use this implementation to generate some word embedding for Japanese.
But we found it gives some words totally the same embeddings which contains some rare characters (Japanese has a large character set).

We are going to find the reason and check if it is due to not optimal nmin and nmax for Japanese.
We want to check the character-level n-gram vocab used by the model but we failed to find it.
Could you please tell us where to find it?

Thanks.

**Comment by timoschick** [comment]
Hi,

the important part for generating the _n_-gram vocab are lines 49 to 59 of `ngram_builder.py`:

        with open(vocab_file, 'r', encoding='utf8') as file:
            for line in file:
                word = line.split()[0]
                ngram_counts.update(self.to_n_gram(word, self.nmin, self.nmax))

        for (ngram, count) in ngram_counts.most_common():
            if count >= ngram_threshold:
                id = len(self.id2ngram)
                self.ngram2id[ngram] = id
                self.id2ngram.append(ngram)

This works as follows: first, each word from the `vocab_file` is loaded, which, by default, contains all words occuring at least 100 times in the training corpus (see `preprocess.py`, parameter `--min_count_target`). For each of these words, all _n_-grams contained therein are added to a Counter `ngram_counts`. Then, only the _n_-grams that occur in at least `ngram_threshold` words (4 by default) are kept. 

Does this help you solve your issue?

**Comment by yuanzhiKe** [comment]
Thank you for your reply. It helps me so much.
