### ISSUE TITLE
About VecMap in the naacl paper

### ISSUE THREAD

**Issue by Hibb-bb** [timoschick/form-context-model#8]
Hi, I'm trying to follow your VecMap experiment in the naacl paper, but I'm not sure which part of the code contains it?
Or you used VecMap's official repo and select downsampled words in the validation set?
Also, the VecMap similariy table in the paper refers to the downsampled words or other words?
Thank you.

**Comment by timoschick** [comment]
Hi @Hibb-bb,
unfortunately, the source code for the VecMap experiment is not contained in this repository as it is mostly based on the official VecMap repository. The downsampled words can be found [here](https://github.com/timoschick/form-context-model/tree/master/vecmap). The VecMap similarity table in the paper refers to the downsampled words.
